### ISSUE TITLE
[KED-1452] Create new example using Kaggle's Titanic dataset

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro-examples#22]
## Description
- We love hosting examples of how Kedro is used and this activity is focused on creating an example using Kedro with Kaggle's Titanic dataset 
- The output of this task is a PR with a Kedro project with a completed ML pipeline for the Kaggle's Titanic dataset 

## Context
- These examples help so many users understand how to use Kedro
- We really do care about expanding our example range

## Possible Implementation
- Use the latest version of Kedro indicated in [`Releases`](https://github.com/quantumblacklabs/kedro/releases)
- Here's a link to the dataset: https://www.kaggle.com/c/titanic/data
- Here's a link to refactored modular code that you could use: https://github.com/FilippoBovo/production-data-science/blob/master/tutorial/d-refactor/titanic/models.py 
- We also have found a user who's done a similar exercise using Kedro here: https://github.com/tatamiya/kedro_titanic

## Possible Alternatives
- You could decide to use another dataset if you want

**Comment by probablyhungryrn** [comment]
I am happy to work on this one!

**Comment by tatamiya** [comment]
Thank you very much for mentioning my repository https://github.com/tatamiya/kedro_titanic.
I'd like to contribute to this issue, too!

**Comment by tatamiya** [comment]
I forked the repository and created a new branch.

Are you considering to make two example sub-directories under the titanic-example directory like the link below?
https://github.com/tatamiya/kedro-examples/tree/titanic-example/kedro-tutorial

**Comment by yetudada** [comment]
Hi @tatamiya! Thank you so much for working on this! I'd actually suggest putting the example here: https://github.com/tatamiya/kedro-examples/tree/titanic-example/kedro-exercises

And then just create the PR and we're ready to commit your amazing work.

**Comment by yetudada** [comment]
An update on this ticket, we'd actually love for this to be turned into a Kedro Starter, see more details here: https://kedro.readthedocs.io/en/latest/02_get_started/06_starters.html

**Comment by yetudada** [comment]
I'm going to close this ticket, as we no longer require a Titanic example to show Kedro users. You can also check out this [**video**](https://www.youtube.com/watch?v=x97ChYDd12U&ab_channel=DataEngineerOne) to see an example Titanic dataset Kedro example explained.
