### ISSUE TITLE
[KED-1381] Update `kedro-tutorial` to the latest version of Kedro

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro-examples#23]
## Description
- We have already created [`Kedro Tutorial`](https://github.com/quantumblacklabs/kedro-examples/tree/master/kedro-exercises/spaceflight) which references the Spaceflights tutorial in our documentation: https://kedro.readthedocs.io/en/latest/03_tutorial/02_tutorial_template.html
- We have to update this project to `kedro 0.15.6` which has changes to how we load data
- Link to the project is here: https://github.com/quantumblacklabs/kedro-examples/tree/master/kedro-exercises/spaceflight

## Context
- These examples help so many users understand how to use Kedro
- We really do care about expanding our example range and keeping it up to date

## Possible Implementation
- Create a new Kedro project called `Kedro Tutorial` and focus on the two most important directories `conf/` and `src/`
- Changes include changes to our Data Catalog in `conf/base/catalog.yml` because we've implemented `fsspec` in our new range of datasets: https://kedro.readthedocs.io/en/latest/04_user_guide/04_data_catalog.html#using-the-data-catalog-with-the-yaml-api

**Comment by 921kiyo** [comment]
Updated the code to 0.15.8 in https://github.com/quantumblacklabs/kedro-examples/pull/31
