### ISSUE TITLE
Improve docs about venv management

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro-examples#40]
## Description

There are docs about [Working with virtual environments](https://github.com/quantumblacklabs/kedro-examples/blob/master/kedro-training/docs/02_virtual-environment.md). These docs are suboptimal cause the example code results in venvs which are not created inside the project but some OS user specific directory. Often this implies need for configuring the venv location in the IDE in use, etc.

## Context

The venv location should enable IDE support for venv auto-detection. The venv location should be independent of the OS in use.

## Possible Implementation

Adding instructions about how to create a venv in `<kedro-project-root>/.venv`.

pipenv/virtualenv:

    python3 -m virtualenv -p python3 .venv
    pipenv install

poetry:

    cd <kedro-project-root>
    poetry config --local virtualenvs.in-project true
    poetry install
    poetry shell
    poetry env info | grep Path
    # will print the venv location

## Possible Alternatives

?

**Comment by yetudada** [comment]
Hi @fkromer! You're welcome to make a PR to update our documentation with these changes. The docs have moved to [`kedro-training`](https://github.com/quantumblacklabs/kedro-training/blob/master/docs/02_virtual-environment.md). I'll close this issue now because it's changed repo.

**Comment by fkromer** [comment]
@yetudada I'm super happy with `kedro` and know how it works now. From my side there is no need to update the docs :smirk:
