### ISSUE TITLE
run.py path wrong?

### ISSUE THREAD

**Issue by wilsonmar** [quantumblacklabs/kedro-examples#5]
## Description
When **kedro doc** displays file:///usr/local/lib/python3.7/site-packages/kedro/html/04_user_guide/03_configuration.html#local-and-base-configuration
coded in https://github.com/quantumblacklabs/kedro/blob/develop/docs/source/04_user_guide/03_configuration.md
the **run.py** file is mentioned in sentence "CONF_ROOT variable in src/run.py."

But IRL the file run.py is actually under kedro-examples/kedro-tutorial/src/**kedro_tutorial**/run.py".

## Context
How has this bug affected you? What were you trying to accomplish?
I've been writing a shell script to do all installs using the example, at
https://github.com/wilsonmar/DevSecOps/blob/master/kedro/kedro-sample-setup.sh

## Steps to Reproduce

1. Install python3, anaconda3, pip3 kedro
2. git clone https://github.com/quantumblacklabs/kedro-examples
3. cd to quantumblacklabs/kedro-examples/kedro-tutorial/src/kedro_tutorial
4. Notice the run.py file is there (not src/sun.py).

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.0
* Python version used (`python -V`): 3.7.2
* Operating system and version: 
      System Version: macOS 10.14.6 (18G87)
      Kernel Version: Darwin 18.7.0

**Comment by 921kiyo** [comment]
Hi @wilsonmar thank you for opening the issue! I think the path in the doc is not correct (also the doc is slightly out of data since in Kedro 0.15.0 , you won't have `CONF_ROOT` in `run.py` anymore). We will update the documentation :)

**Comment by 921kiyo** [comment]
`CONF_ROOT` is [inside the `KedroContext` class](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/context/context.py#L71) since Kedro 0.15.0. If you want to modify the configuration paths, you can do so by overriding it from the `ProjectContext` class in `src/kedro_tutorial/run.py` as follows:

```python
class ProjectContext(KedroContext):
    CONF_ROOT = "new-path"
    # ...
```

**Comment by 921kiyo** [comment]
Fixed in https://github.com/quantumblacklabs/kedro/commit/df9d61a43740beecc784677c77eb06b56c5914be
