### ISSUE TITLE
label:"help wanted" Need procedure for running iris example

### ISSUE THREAD

**Issue by vjkr** [quantumblacklabs/kedro-examples#56]
I keep getting lost inside the folders
Documents are bit high tech I guess. Can anyone direct me to run iris project
thanks in advance

**Comment by stichbury** [comment]
Hi there @vjkr!

You are looking at the docs here? https://kedro.readthedocs.io/en/stable/02_get_started/05_example_project.html

Have you already worked through the earlier docs to ensure you meet the [pre-requisites](https://kedro.readthedocs.io/en/stable/02_get_started/01_prerequisites.html) and have [installed Kedro](https://kedro.readthedocs.io/en/stable/02_get_started/02_install.html) in a virtual environment?

When you run `kedro info` what do you see?

What version do you have?

You should then be able to follow the docs for the Iris example:
(1) [create a project with `kedro new`](https://kedro.readthedocs.io/en/stable/02_get_started/04_new_project.html) and confirm Y to build in the iris example code at the final prompt

That will give you the project, creating a project directory to store all the subfolders and code.

(2) Change directory into the project directory and type `kedro run`

What do you see?

**Comment by vjkr** [comment]
Hi @stichbury !
** It worked!! Thanks! **
I had completed all previous steps. But I was unable to comprehend that `kedro run` is in itself a command. Till now I was familiar with `python somefile.py` .

Just for information kedro run returned following error.
**ModuleNotFoundError: No module named 'pandas'**
I fixed it by running `conda install pandas` 

Thanks a ton!

**Comment by stichbury** [comment]
Great! Thanks for letting me know. I'll take another look at those docs and see if I can further clarify things. Your feedback is really helpful for us to improve the docs, so let me know if you hit other issues as your Kedro journey continues. Happy exploring 🗺️

**Comment by vjkr** [comment]
@stichbury Honestly the docs are great. This is my first time referring such docs in coding. I will need all the directions you may offer. 

Three things
1. I need help regarding understanding the code flow. I know iris example. But unable to follow all the folders/files/CLI. 

2. I understood importance of <kedro install> when I hit a barricade during <kedro test>. <kedro install> helped. Thanks !!

3. I named my project
<kedroiris>
When I searched for location of my pipeline, it is at
<src/kedroirispackages/pipelines/data_engineering/pipeline.py>

So for the <getting_started> project in readthedocs I guess location should be
<src/getting_startedpackages/pipelines/data_engineering/pipeline.py>
instead of 
<src/getting_started/pipelines/data_engineering/pipeline.py>

*Also forgive me for unconventional questions/posting styles. I am new to everything.*

Thanks!!

**Comment by yetudada** [comment]
@vjkr You can join us on [Discourse](https://discourse.kedro.community/) and I hope that you got all the help that you needed 🚀 I'll close this issue now.
